/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AEstrella;

//import javax.swing.SwingConstants;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.*;
/**
 *
 * @author Usuario
 */
public class GUI extends javax.swing.JFrame {
    int matrizInicial[][];
    int matrizMeta[][];
	char [] NM1= new char [9];
	char [] NM2= new char [9];
	int contador1= 0;
	int contador2=0;
    public GUI() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = new javax.swing.JPanel();
        etiquetaPI = new java.awt.Label();
        etiquetaPM = new java.awt.Label();
        puzzleInicial = new javax.swing.JPanel();
        ini00 = new javax.swing.JTextField();
        ini12 = new javax.swing.JTextField();
        ini01 = new javax.swing.JTextField();
        ini22 = new javax.swing.JTextField();
        ini11 = new javax.swing.JTextField();
        ini02 = new javax.swing.JTextField();
        ini10 = new javax.swing.JTextField();
        ini21 = new javax.swing.JTextField();
        ini20 = new javax.swing.JTextField();
        puzzleMeta = new javax.swing.JPanel();
        fin01 = new javax.swing.JTextField();
        fin00 = new javax.swing.JTextField();
        fin02 = new javax.swing.JTextField();
        fin10 = new javax.swing.JTextField();
        fin11 = new javax.swing.JTextField();
        fin12 = new javax.swing.JTextField();
        fin20 = new javax.swing.JTextField();
        fin21 = new javax.swing.JTextField();
        fin22 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método de busqueda A*");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        etiquetaPI.setText("Puzzle Inicial");

        etiquetaPM.setText("Puzzle Meta");

        ini00.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ini00ActionPerformed(evt);
            }
        });
        ini00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini01.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ini01ActionPerformed(evt);
            }
        });
        ini01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini02.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        ini20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ini20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'1');
            }
        });

        javax.swing.GroupLayout puzzleInicialLayout = new javax.swing.GroupLayout(puzzleInicial);
        puzzleInicial.setLayout(puzzleInicialLayout);
        puzzleInicialLayout.setHorizontalGroup(
            puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzleInicialLayout.createSequentialGroup()
                .addComponent(ini00, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ini01, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ini02, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(puzzleInicialLayout.createSequentialGroup()
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(puzzleInicialLayout.createSequentialGroup()
                        .addComponent(ini10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ini11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puzzleInicialLayout.createSequentialGroup()
                        .addComponent(ini20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ini21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ini22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        puzzleInicialLayout.setVerticalGroup(
            puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzleInicialLayout.createSequentialGroup()
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        fin01.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin00.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin00ActionPerformed(evt);
            }
        });
        fin00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin02.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        fin22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fin22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarCampo(evt,'2');
            }
        });

        javax.swing.GroupLayout puzzleMetaLayout = new javax.swing.GroupLayout(puzzleMeta);
        puzzleMeta.setLayout(puzzleMetaLayout);
        puzzleMetaLayout.setHorizontalGroup(
            puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puzzleMetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fin00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(fin10)
                    .addComponent(fin20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fin11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(fin01, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fin21, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fin02, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(fin12)
                    .addComponent(fin22))
                .addGap(4, 4, 4))
        );
        puzzleMetaLayout.setVerticalGroup(
            puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzleMetaLayout.createSequentialGroup()
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Abiertos", "Cerrados"
            }
        ));
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
        }

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setEditable(false);
        jScrollPane1.setViewportView(textArea);

        buscar.setActionCommand("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(puzzleInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puzzleMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(puzzleInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puzzleMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarCampo(java.awt.event.KeyEvent evt, char x) {//GEN-FIRST:event_validarCampo
        char c=evt.getKeyChar();
        boolean repetido=false;
        if(x=='1'){
        	for(int i=0;i<contador1;i++){
            	if(NM1[i]==c){
              		repetido=true;
           		}
       		}
        }else{
        	for(int i=0;i<contador2;i++){
            	if(NM2[i]==c){
              		repetido=true;
           		}
       		}
        }
        if(evt.getSource() instanceof JTextField ){
            if(((JTextField)(evt.getSource())).getText().length()==1)
                evt.consume(); 
        }
        if(!Character.isDigit(c) && c!=KeyEvent.VK_BACKSPACE || repetido) { 
            getToolkit().beep();            
            evt.consume();
        }else{
        	if(x=='1'){        		
	            NM1[contador1]=c;
	            contador1++;
        	}else{
        		NM2[contador2]=c;
	            contador2++;
        	}
        }
       
    }//GEN-LAST:event_validarCampo

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if(evt.getActionCommand().equals("Buscar")){
            bloquearCamposTexto();
            textArea.setText("");
            tabla.removeAll();
            matrizInicial = new int[3][3];
            matrizMeta = new int[3][3];
            llenarMatrices(matrizInicial, matrizMeta);
            BusquedaAEstrella aEstrella = new BusquedaAEstrella(matrizInicial, matrizMeta);
            
            desbloquearCamposTexto();
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void ini00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ini00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ini00ActionPerformed

    private void fin00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fin00ActionPerformed

    private void ini01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ini01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ini01ActionPerformed

    public void llenarMatrices(int[][] mI, int[][] mM){
        mI[0][0]=Integer.parseInt(ini00.getText());mI[0][1]=Integer.parseInt(ini01.getText());mI[0][2]=Integer.parseInt(ini02.getText());
        mI[1][0]=Integer.parseInt(ini10.getText());mI[1][1]=Integer.parseInt(ini11.getText());mI[1][2]=Integer.parseInt(ini12.getText());
        mI[2][0]=Integer.parseInt(ini20.getText());mI[2][1]=Integer.parseInt(ini21.getText());mI[2][2]=Integer.parseInt(ini22.getText());

        mM[0][0]=Integer.parseInt(fin00.getText());mM[0][1]=Integer.parseInt(fin01.getText());mM[0][2]=Integer.parseInt(fin02.getText());
        mM[1][0]=Integer.parseInt(fin10.getText());mM[1][1]=Integer.parseInt(fin11.getText());mM[1][2]=Integer.parseInt(fin12.getText());
        mM[2][0]=Integer.parseInt(fin20.getText());mM[2][1]=Integer.parseInt(fin21.getText());mM[2][2]=Integer.parseInt(fin22.getText());
    }
    public void bloquearCamposTexto(){
        ini00.setEditable(false);ini01.setEditable(false);ini02.setEditable(false);
        ini10.setEditable(false);ini11.setEditable(false);ini12.setEditable(false);
        ini20.setEditable(false);ini21.setEditable(false);ini22.setEditable(false);
        
        fin00.setEditable(false);fin01.setEditable(false);fin02.setEditable(false);
        fin10.setEditable(false);fin11.setEditable(false);fin12.setEditable(false);
        fin20.setEditable(false);fin21.setEditable(false);fin22.setEditable(false);
    }
    
    public void desbloquearCamposTexto(){
        ini00.setEditable(true);ini01.setEditable(true);ini02.setEditable(true);
        ini10.setEditable(true);ini11.setEditable(true);ini12.setEditable(true);
        ini20.setEditable(true);ini21.setEditable(true);ini22.setEditable(true);
        
        fin00.setEditable(true);fin01.setEditable(true);fin02.setEditable(true);
        fin10.setEditable(true);fin11.setEditable(true);fin12.setEditable(true);
        fin20.setEditable(true);fin21.setEditable(true);fin22.setEditable(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscar;
    private java.awt.Label etiquetaPI;
    private java.awt.Label etiquetaPM;
    public javax.swing.JTextField fin00;
    public javax.swing.JTextField fin01;
    public javax.swing.JTextField fin02;
    public javax.swing.JTextField fin10;
    public javax.swing.JTextField fin11;
    public javax.swing.JTextField fin12;
    public javax.swing.JTextField fin20;
    public javax.swing.JTextField fin21;
    public javax.swing.JTextField fin22;
    public javax.swing.JTextField ini00;
    public javax.swing.JTextField ini01;
    public javax.swing.JTextField ini02;
    public javax.swing.JTextField ini10;
    public javax.swing.JTextField ini11;
    public javax.swing.JTextField ini12;
    public javax.swing.JTextField ini20;
    public javax.swing.JTextField ini21;
    public javax.swing.JTextField ini22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel puzzleInicial;
    private javax.swing.JPanel puzzleMeta;
    public javax.swing.JTable tabla;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
